name: runna
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.4.1
  riverpod_annotation: ^2.3.5
  flutter_riverpod: ^2.5.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  go_router: ^17.1.0
  dio: ^5.9.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  riverpod_generator: ^2.6.3
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  generate: true
